on: pull_request

jobs:
  evaluate_iam_policy:
    runs-on: ubuntu-latest
    name: Evaluate IAM Policy
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        shell: bash
        run: |
          PULL_NUMBER=$(jq --raw-output .pull_request.number "${GITHUB_EVENT_PATH}")
          curl \
            -H "Authorization: token ${{ secrets.IAMBOT_GITHUB_TOKEN }}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${PULL_NUMBER}/comments \
            -d '{"body":"Comment Test"}'
