on: pull_request

jobs:
  evaluate_iam_policy:
    runs-on: ubuntu-latest
    name: Evaluate IAM Policy
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        shell: bash
        run: |
          echo $TOKEN
          echo $IAMBOT_GITHUB_TOKEN
          echo ${{ secrets.IAMBOT_GITHUB_TOKEN }}