on: pull_request

jobs:
  evaluate_iam_policy:
    runs-on: ubuntu-latest
    name: Evaluate IAM Policy
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install iamfast-js
        run: npm i -g iamfast

      - name: Comment PR
        shell: bash
        run: |
          POLICY=$(iamfast-js test1.js | sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g')
          echo $POLICY
          PULL_NUMBER=$(jq --raw-output .pull_request.number "${GITHUB_EVENT_PATH}")
          echo "{\"body\":\"Generated IAM Policy:\n\n\`\`\`\n${POLICY}\n\`\`\`\"}"
          curl \
            -H "Authorization: token ${{ secrets.IAMBOT_GITHUB_TOKEN }}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${PULL_NUMBER}/comments \
            -d "{\"body\":\"Generated IAM Policy:\n\n\n${POLICY}\n\"}"
